=== HyperlinkVR/HyperlinkVR/schemas/AuthManifest_v2.json
{
    "$id": "https://hyperlink.surf/schemas/AuthManifest_v2.json",
    "version": 2,
    "title": "HyperlinkVR - Auth Manifest (version 2)",
    "description": "An auth manifest for HyperlinkVR to describe the authentication methods supported by a site, as well as friendly display properties, under the .well-known/hyperlinkvr/auth-manifest.json path. This schema is version 2.",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "properties": {
        "$schema": {
            "default": "https://hyperlink.surf/schemas/AuthManifest_v2.json",
            "type": "string"
        },
        "version": {
            "type": "integer",
            "const": 2
        },
        "methods": {
            "minItems": 1,
            "type": "array",
            "items": {
                "type": "string",
                "enum": [
                    "static",
                    "jwt",
                    "passkey"
                ]
            }
        },
        "host_name": {
            "type": "string"
        },
        "host_description": {
            "type": "string"
        },
        "host_icon": {
            "type": "string",
            "format": "uri"
        },
        "open_for_registration": {
            "default": true,
            "type": "boolean"
        },
        "static_submit_hint": {
            "type": "string"
        },
        "hypergram_read_api_base": {
            "type": "string",
            "format": "uri"
        }
    },
    "required": [
        "version",
        "methods"
    ],
    "if": {
        "required": [
            "static_submit_hint"
        ]
    },
    "then": {
        "properties": {
            "methods": {
                "contains": {
                    "const": "static"
                }
            }
        },
        "errorMessage": {
            "properties": {
                "methods": "static_submit_hint should not be provided if static auth is not supported"
            }
        }
    }
}

=== HyperlinkVR/HyperlinkVR/.well-known/hyperlinkvr/auth-manifest.json
{
    "$schema": "https://hyperlink.surf/schemas/AuthManifest_v2.json",
    "version": 2,
    "methods": [
        "static"
    ],
    "host_name": "HyperlinkVR",
    "open_for_registration": true,
    "static_submit_hint": "If you're a key contributor, open a PR on the web repo",
    "hypergram_read_api_base": "https://hypergram-api.hyperlink.surf"
}
