=== HyperlinkVR/HyperlinkVR/schemas/WorldMetadata_v1.json
{
    "$id": "https://hyperlink.surf/schemas/WorldMetadata_v1.json",
    "version": 1,
    "title": "HyperlinkVR - World Metadata (version 1)",
    "description": "Metadata for a HyperlinkVR world, including title, description, author, and thumbnail. This schema is version 1.",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "properties": {
        "$schema": {
            "default": "https://hyperlink.surf/schemas/WorldMetadata_v1.json",
            "type": "string"
        },
        "version": {
            "type": "integer",
            "const": 1
        },
        "title": {
            "type": "string",
            "minLength": 2,
            "maxLength": 32
        },
        "description": {
            "type": "string",
            "maxLength": 512
        },
        "category": {
            "type": "string",
            "enum": [
                "social",
                "game",
                "art",
                "music",
                "education",
                "utility",
                "spatial_computing",
                "other"
            ]
        },
        "tags": {
            "maxItems": 8,
            "type": "array",
            "items": {
                "type": "string",
                "minLength": 1,
                "maxLength": 16,
                "pattern": "^[\\p{L}\\p{N}_-]+$"
            }
        },
        "author": {
            "type": "object",
            "properties": {
                "username": {
                    "type": "string",
                    "minLength": 3,
                    "maxLength": 64
                },
                "signature": {
                    "type": "string"
                }
            },
            "required": [
                "username"
            ]
        },
        "additional_contributors": {
            "maxItems": 20,
            "type": "array",
            "items": {
                "anyOf": [
                    {
                        "type": "object",
                        "properties": {
                            "username": {
                                "type": "string",
                                "minLength": 3,
                                "maxLength": 64
                            },
                            "signature": {
                                "type": "string"
                            },
                            "role": {
                                "default": "contributor",
                                "type": "string",
                                "enum": [
                                    "contributor",
                                    "co-owner",
                                    "developer",
                                    "designer",
                                    "artist",
                                    "musician",
                                    "tester",
                                    "manager",
                                    "social",
                                    "hosting",
                                    "shoutout",
                                    "other"
                                ]
                            }
                        },
                        "required": [
                            "username"
                        ]
                    },
                    {
                        "type": "string",
                        "minLength": 3,
                        "maxLength": 64
                    }
                ]
            }
        },
        "thumbnail": {
            "type": "string"
        },
        "gallery": {
            "maxItems": 5,
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "theme_color": {
            "anyOf": [
                {
                    "type": "integer",
                    "minimum": 0,
                    "maximum": 16777215
                },
                {
                    "type": "string",
                    "pattern": "^#([0-9a-fA-F]{6})$"
                }
            ]
        },
        "supports": {
            "default": {
                "vr": "maybe",
                "flat": "maybe",
                "low_power": "maybe",
                "browser": true,
                "teleport": true
            },
            "type": "object",
            "properties": {
                "vr": {
                    "default": "maybe",
                    "type": "string",
                    "enum": [
                        "no",
                        "maybe",
                        "yes"
                    ]
                },
                "flat": {
                    "default": "maybe",
                    "type": "string",
                    "enum": [
                        "no",
                        "maybe",
                        "yes"
                    ]
                },
                "low_power": {
                    "default": "maybe",
                    "type": "string",
                    "enum": [
                        "no",
                        "maybe",
                        "yes"
                    ]
                },
                "browser": {
                    "default": true,
                    "type": "boolean"
                },
                "teleport": {
                    "default": true,
                    "type": "boolean"
                }
            }
        },
        "languages": {
            "default": "any",
            "anyOf": [
                {
                    "type": "string",
                    "const": "any"
                },
                {
                    "minItems": 1,
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            ]
        },
        "max_players": {
            "default": 32,
            "type": "integer",
            "minimum": 1,
            "maximum": 32
        },
        "recommended_players": {
            "default": 8,
            "type": "integer",
            "minimum": 1,
            "maximum": 32
        },
        "content_flags": {
            "type": "array",
            "items": {
                "type": "string",
                "enum": [
                    "cartoon_violence",
                    "realistic_violence",
                    "intense_violence",
                    "sexual_content",
                    "mild_horror",
                    "horror",
                    "drugs",
                    "strong_language",
                    "gambling",
                    "flashing_lights",
                    "loud_sounds",
                    "ugc",
                    "real_money",
                    "other"
                ]
            }
        },
        "vr_comfort": {
            "type": "string",
            "enum": [
                "comfortable",
                "moderate",
                "intense"
            ]
        },
        "preloads": {
            "maxItems": 64,
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "endorsements": {
            "maxItems": 20,
            "type": "array",
            "items": {
                "type": "string",
                "format": "uri"
            }
        },
        "homepage": {
            "type": "string",
            "format": "uri"
        },
        "repo": {
            "type": "string",
            "format": "uri"
        },
        "license_spdx": {
            "type": "string"
        }
    },
    "required": [
        "version",
        "title"
    ],
    "if": {
        "properties": {
            "recommended_players": {
                "type": "number"
            },
            "max_players": {
                "type": "number"
            }
        },
        "required": [
            "recommended_players",
            "max_players"
        ]
    },
    "then": {
        "properties": {
            "recommended_players": {
                "type": "number",
                "maximum": {
                    "$data": "1/max_players"
                }
            }
        }
    }
}

=== HyperlinkVR/HyperlinkVR/apps/website/public/minigolf/hvr-world.json
{
    "$schema": "https://hyperlink.surf/schemas/WorldMetadata_v1.json",
    "version": 1,
    "supports": {
        "vr": "yes",
        "flat": "yes",
        "low_power": "maybe",
        "teleport": true
    },
    "languages": ["en"],
    "max_players": 8,
    "recommended_players": 4,
    "title": "Minigolf",
    "category": "game",
    "tags": ["golf", "ball"],
    "author": {
        "username": "ollie@hyperlink.surf",
        "signature": "gEiFq2uw9GJITlXigu3xcIa9DufJkpUWKPb9Mzsgw8t682C7eMo+Gv1CTBXNoZkvHUrDcbU78kcApkFq+5JADA=="
    },
    "additional_contributors": [],
    "gallery": [],
    "thumbnail": "https://hyperlink.surf/minigolf/thumbnail.jpg",
    "content_flags": [],
    "vr_comfort": "moderate",
    "preloads": [],
    "endorsements": []
}

=== HyperlinkVR/HyperlinkVR/clubhouse/hvr-world.json
{
    "$schema": "https://hyperlink.surf/schemas/WorldMetadata_v1.json",
    "version": 1,
    "title": "Clubhouse",
    "category": "social",
    "tags": [
        "hangout"
    ],
    "author": {
        "username": "ollie@hyperlink.surf",
        "signature": "xwPFXFVYUAA+ytWmsu1HMzBMkisOMa1AH3P8ZuiDaWf+OPWZXeqph7KqLWO1ARiVO/L9Js7FSZXCMjMoTT2qAQ=="
    },
    "additional_contributors": [],
    "gallery": [],
    "theme_color": 10499793,
    "supports": {
        "vr": "yes",
        "flat": "yes",
        "low_power": "yes",
        "teleport": true
    },
    "languages": "any",
    "max_players": 32,
    "recommended_players": 32,
    "content_flags": [],
    "vr_comfort": "comfortable",
    "preloads": [],
    "endorsements": [
        "https://hyperlink.surf/minigolf"
    ],
    "homepage": "https://hyperlink.surf"
}

=== HyperlinkVR/HyperlinkVR/apps/website/public/defendthecore/hvr-world.json
{
    "$schema": "https://hyperlink.surf/schemas/WorldMetadata_v1.json",
    "version": 1,
    "title": "Defend the Core!",
    "category": "game",
    "tags": ["defence", "robots", "sci-fi", "wave"],
    "author": {
        "username": "ollie@hyperlink.surf",
        "signature": "VuRFAr48MV1J+6PNScVcR13sUm11BQwoPgFZuPkcfX1ayVJEMVVIwe7TqP0kO4eJSJQwkCNConlRTmBmbM3SBQ=="
    },
    "additional_contributors": [],
    "thumbnail": "https://hyperlink.surf/defendthecore/thumbnail.jpg",
    "gallery": [],
    "theme_color": 7257087,
    "supports": {
        "vr": "yes",
        "flat": "yes",
        "low_power": "yes",
        "teleport": true
    },
    "languages": "any",
    "max_players": 8,
    "recommended_players": 4,
    "content_flags": ["cartoon_violence"],
    "vr_comfort": "comfortable",
    "preloads": [],
    "endorsements": []
}
